config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'

  devise_for :users,
      path: :gurus,
      path_names: { sign_in: :login, sign_out: :logout },
      controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
       resources :answers, shallow: true, except: :index
      end
    end

    resources :gists, only: :index
    resources :badges
  end

  resources :feedbacks, only: %i[new create]
  resources :badges, only: %i[index]

end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :users_badges
  has_many :users, through: :users_badges

  validates :name, :image, presence: true

  RULES = [
    ['All category tests are completed.', :category_tests_completed],
    ['Test first try is successful.', :test_first_try_successful],
    ['All level tests are completed.', :level_tests_completed]
  ]

  def self.images
    images_path = 'app/assets/images/'
    images = Dir.glob("app/assets/images/badges/*")
    images.each {|image| image[images_path] = ''}
  end
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController

  before_action :find_badge, only: %i[show edit update destroy]

  def index
    @user_badges = current_user.badges
    @badges = Badge.all
  end

  def show
  end

  def new
    @badge = Badge.new
  end

  def create
    @badge = Badge.new(badge_params)

    if @badge.save
      redirect_to admin_badge_path(@badge), notice: t('.success')
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badge_path(@badge)
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy
    redirect_to badges_path
  end

  private

  def find_badge
    @badge = Badge.find(params[:id])
  end

  def badge_params
    params.require(:badge).permit(:name, :image, :rule)
  end

end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController

  def index
    @badges = Badge.all
    @user_badges = current_user.badges
  end

  def show
    @badge = Badge.find(params[:id])
  end

  private
    def badge_params
      params.require(:badge).permit(:name, :image, :url)
    end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/views/admin/badges/_badge.html.erb
<tr>
  <td class="align-middle">
    <%= badge.name %>
  </td>
  <td>
    <%= image_tag badge.image, style: 'height:10;width:10;margin-bottom:10px;' %>
  </td>
  <td class="align-middle">
    <%= link_to t('.show'), admin_badge_path(badge) %>
  </td>
  <td class="align-middle">
    <%= link_to t('.edit'), edit_admin_badge_path(badge) %>
  </td>
  <td class="align-middle">
    <%= link_to t('.delete'),
      admin_badge_path(badge),
      method: :delete,
      data: {confirm: t('.confirm') } %>
  </td>
</tr>

app/views/admin/badges/_form.html.erb
<div class="row mt-3">
  <div class="col col-md-4">
    <div class="card border-primary">
      <div class="card-body">

        <%= form_with model: [:admin, @badge], local: true do |form| %>
          <%= render 'shared/errors', resource: @badge %>
          <div class="form-group">

          <p>
            <%= form.label :name %><br>
            <%= form.text_field :name, class: 'form-control' %>
          </p><br>

          <p>
            <%= form.label :image %><br>
            <%= form.select :image, options_for_select(Badge.images), prompt: true, class: 'form-control' %>
          </p><br>

          <p>
            <%= form.label :rule %><br>
            <%= form.select :rule, options_for_select(Badge::RULES), prompt: true, class: 'form-control' %>
          </p><br>

          <p>
            <%= form.label :value %><br>
            <%= form.text_field :value, class: 'form-control' %>
          </p><br>

          <%= form.submit "Enter", class: 'btn btn-primary' %>
          </div>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/admin/badges/edit.html.erb
<h1><%= t('.edit_badge') %> <%= @badge.name %></h1>

<%= render 'form' %>
<%= link_to t('back'), admin_badges_path %>

app/views/admin/badges/index.html.erb
<h1><%= t('.header') %></h1>

<p><mark><strong>
    <%= link_to t('.new_badge'), new_admin_badge_path %>
</strong></mark></p>

<%= render 'shared/errors', resource: @badge %>

<div class="row mt-5">
  <div class="col-md-12">
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">
            <%= t('.name') %>
          </th>
          <th scope="col"><%= t('.image') %></th>
          <th scope="col" colspan="4"><%= t('.actions') %></th>
        </tr>
      </thead>
      </tbody>
        <%= render @badges %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/badges/new.html.erb
<h1><%= t('.create_new_badge') %></h1>

<%= render 'form' %>
<%= link_to t('back'), admin_badges_path %>

app/views/admin/badges/show.html.erb
<div class="row mt-3">
  <div class="col col-md-6">
    <%= link_to t('edit'), edit_admin_badge_path(@badge) %>
    <%= link_to t('back'), admin_badges_path %>
    <p>
      <strong><%= t('.name') %></strong>
      <%= @badge.name %>
    </p>
    <p>
      <strong><%= t('.image') %></strong>
      <%= image_tag @badge.image, style: 'height:10;width:10;margin-bottom:10px;' %>
    </p>
  </div>
</div>