config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'

  devise_for :users,
      path: :gurus,
      path_names: { sign_in: :login, sign_out: :logout },
      controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
       resources :answers, shallow: true, except: :index
      end
    end

    resources :gists, only: :index
    resources :badges
  end

  resources :feedbacks, only: %i[new create]
  resources :badges, only: %i[index]

end

app/models/admin.rb
class Admin < User 
  validates :first_name, :last_name, presence: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  scope :correct_answers, -> { where(correct: true) }

  validates :title, presence: true
  validate :answers_count, on: :create

  private

  def answers_count
    errors.add(:self, 'Question must have only 1-4 answers') unless (0..3).include?(question.answers.count)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :users_badges
  has_many :users, through: :users_badges

  validates :name, :image, presence: true

  RULES = [
    ['All category tests are completed.', :category_tests_completed],
    ['Test first try is successful.', :test_first_try_successful],
    ['All level tests are completed.', :level_tests_completed]
  ]

  def self.images
    images_path = 'app/assets/images/'
    images = Dir.glob("app/assets/images/badges/*")
    images.each {|image| image[images_path] = ''}
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests
  default_scope { order(title: :asc) }

  validates :title, presence: true
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user

  validates :title, :body, presence: true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :question
  belongs_to :user

  validates :url, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  has_many :test_passages, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :users, through: :test_passages
  belongs_to :category
  belongs_to :author, class_name: 'User'

  scope :easy, -> { where(level: [0..1]) }
  scope :middle, -> { where(level: [2..4]) }
  scope :complicated, -> { where(level: [5..Float::INFINITY]) }
  scope :by_category, -> (category) { joins(:category).where(categories: {title: category}) }

  validates :title, presence: true
  validates :level, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :title, uniqueness: { scope: :level }

  def self.get_tests_by_category(category)
    by_category(category).order(title: :desc).pluck(:title)
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :test
  belongs_to :user
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_or_next_question, on: %i[create update]

  SUCCESS_SCORE = 85

  def completed?
    current_question.nil? || no_time?
  end

  def accept!(answer_ids)
    if correct_answer?(answer_ids || [])
      self.correct_questions += 1
    end

    save!
  end

  def success_percentage
    100*correct_questions/test.questions.count
  end

  def successful?
    success_percentage >= SUCCESS_SCORE
  end

  def current_question_number
    if completed?
      test.questions.count
    else
      test.questions.count - next_questions.count
    end
  end

  def deadline_time
    created_at + test.allotted_time.minutes
  end

  def time_left
    deadline_time - Time.now
  end

  def time_left_string
    timer = time_left
    if timer > 0
      (timer/60).to_i.to_s + ':' + (timer%60).to_i.to_s
    else
      '0:00'
    end
  end

  def no_time?
    return false if test.allotted_time == nil
    if time_left > 0
      false
    else
      true
    end
  end

  private

  def before_validation_set_first_or_next_question
    if new_record?
      self.current_question = test.questions.first if test.present?
    else
      self.current_question = next_question
    end
  end

  def correct_answer?(answer_ids)
    correct_answers_count = correct_answers.count
    (correct_answers_count == correct_answers.where(id: answer_ids).count) &&
    correct_answers_count == answer_ids.count
  end

  def correct_answers
    current_question.answers.correct_answers
  end

  def next_questions
    test.questions.order(:id).where('id > ?', self.current_question.id)
  end

  def next_question
    next_questions.first
  end

end

app/models/user.rb
class User < ApplicationRecord

  devise  :database_authenticatable,
          :registerable,
          :recoverable,
          :rememberable,
          :validatable,
          :trackable,
          :confirmable

  EMAIL_PATTERN_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  has_many :test_passages
  has_many :tests, through: :test_passages
  has_many :own_tests, class_name: 'Test', foreign_key: :author_id
  has_many :gists
  has_many :feedbacks
  has_many :users_badges
  has_many :badges, through: :users_badges

  validates :email,
    presence: true,
    format: { with: EMAIL_PATTERN_REGEX },
    uniqueness: { case_sensitive: false }

  def get_passing_tests_by_level(level)
    tests.where(level: level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def admin?
    is_a?(Admin)
  end

end

app/models/users_badge.rb
class UsersBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController

  before_action :authenticate_user!
  before_action :find_test, only: %i[start]

  def index
    @tests = Test.all
  end

  def start
    current_user.tests.push(@test)
    redirect_to current_user.test_passage(@test)
  end

  private

  def find_test
    @test = Test.find(params[:id])
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  BOOTSTRAP_ALERT_CLASSES = {alert: 'alert-warning',
                             error: 'aler-danger',
                             success: 'alert-success',
                             notice: 'alert-info' }

  def footer_year
    Time.new.year
  end

  def github_url(author, repo, tag_body)
    link_to tag_body, "https://github.com/#{author}/#{repo}", target: '_blank'
  end

  def flash_message(alert)
    if flash[alert]
      content_tag :p, flash[alert], class: 'flash alert'
    else
      ''
    end
  end

  def gist_hash(gist_url)
    gist_url['https://gist.github.com/'.length..]
  end

end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    line_end = "#{question.test.title} Question"
    if question.new_record?
      "Create #{line_end}"
    else
      "Edit #{line_end}"
    end
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper

  def success_color_string(test_passage)
    if test_passage.successful?
      string_color = 'green'
      result_string = t('test_was_passed')
    else
      string_color = 'red'
      result_string = t('test_was_failed')
    end

    questions_string = t('questions_correct')
    "<span style='color: #{string_color}'>#{test_passage.success_percentage}%</span> #{questions_string}<p>#{result_string}</p>".html_safe
  end
end

app/helpers/tests_helper.rb
module TestsHelper

  TEST_LEVELS = { 0 => :easy, 1 => :elementary, 2 => :advanced, 3 => :hard }.freeze

  def test_level(test)
    TEST_LEVELS[test.level] || :hero
  end

  def questions_count(test)
    test.questions.count
  end
end

app/views/admin/_nav.html.erb
<nav class="navbar navbar-light bg-light">
  <ul class="nav nav-pills">
    <li class="nav-item">
      <%= link_to 'TestGuru', root_path, class: 'nav-link' %>
    </li>

    <% if current_user.admin? %>
      <li class="nav-item">
        <%= link_to t('admin_panel'), admin_tests_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to t('badges_panel'), admin_badges_path, class: 'nav-link' %>
      </li>

    <% end %>
  </ul>

  <span class="navbar-text">
    <div class="nav nav-admin">
      <%= t('.welcome') %> 
      <b class="nav-admin user-email"> <%= current_user.email %> </b> 
      <%= t('.guru') %> | 
      <%= link_to t('logout'), destroy_user_session_path, method: :delete  %>
    </div>
  </span>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

   <title>Admin Panel | TestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'admin/nav' %>

    <div class="container-fluid p-3 mb-2">
      <%= render 'shared/flash' %>
      <%= yield %>
      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>TestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>

    <div class="container-fluid p-3 mb-2">
      <%= render 'shared/flash' %>
      <%= yield %>
      <%= render 'shared/footer' %>
    </div>

 </body>
</html>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.present? %>
  <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>
    <h2>
      <%= t('.header', count: resource.errors.count) %>:
   </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <div class="alert <%= ApplicationHelper::BOOTSTRAP_ALERT_CLASSES[key.to_sym] %>">
    <%= content_tag :p, message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-dark text-center text-white fixed-bottom">
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
      <font size="2">
        <b> <%= github_url('ostbob', 'test-guru', 'TestGuru') %> </b><br>
        <b><a href="https://thinknetica.com/" target="_blank">Учебный проект в онлайн-школе Thinknetica</a></b><br>
        <b><%= link_to 'Feedback', new_feedback_path %></b></br>
        Copyright (c) ostbob, <%= footer_year %>.
      </font>
    <br>
  </div>
</footer>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-light bg-light px-3">
  <ul class="nav nav-pills">
    <li class="nav-item">
      <%= link_to 'TestGuru', root_path, class: 'nav-link' %>
    </li>

    <% if current_user != nil && !current_user.admin? %>
      <li class="nav-item">
        <%= link_to t('badges_panel'), badges_path, class: 'nav-link' %>
      </li>
    <% end %>

    <% if current_user != nil && current_user.admin? %>
      <li class="nav-item">
        <%= link_to t('admin_panel'), admin_tests_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to t('badges_panel'), admin_badges_path, class: 'nav-link' %>
      </li>
    <% end %>
  </ul>

  <span class="navbar-text">
    <% if user_signed_in? %>
        <%= t('welcome') %> <b><%= current_user.email %></b> <%= t('guru') %>. | 
        <%= link_to t('logout'), destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to t('register'), new_user_registration_path %> | 
      <%= link_to t('login'), new_user_session_path %>
    <% end %>
  </span>
</nav>