config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'

  devise_for :users,
      path: :gurus,
      path_names: { sign_in: :login, sign_out: :logout },
      controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
       resources :answers, shallow: true, except: :index
      end
    end

    resources :gists, only: :index
    resources :badges
  end

  resources :feedbacks, only: %i[new create]
  resources :badges, only: %i[index]

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :test
  belongs_to :user
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_or_next_question, on: %i[create update]

  SUCCESS_SCORE = 85

  def completed?
    current_question.nil? || no_time?
  end

  def accept!(answer_ids)
    if correct_answer?(answer_ids || [])
      self.correct_questions += 1
    end

    save!
  end

  def success_percentage
    100*correct_questions/test.questions.count
  end

  def successful?
    success_percentage >= SUCCESS_SCORE
  end

  def current_question_number
    if completed?
      test.questions.count
    else
      test.questions.count - next_questions.count
    end
  end

  def deadline_time
    created_at + test.allotted_time.minutes
  end

  def time_left
    deadline_time - Time.now
  end

  def time_left_string
    timer = time_left
    if timer > 0
      (timer/60).to_i.to_s + ':' + (timer%60).to_i.to_s
    else
      '0:00'
    end
  end

  def no_time?
    return false if test.allotted_time == nil
    if time_left > 0
      false
    else
      true
    end
  end

  private

  def before_validation_set_first_or_next_question
    if new_record?
      self.current_question = test.questions.first if test.present?
    else
      self.current_question = next_question
    end
  end

  def correct_answer?(answer_ids)
    correct_answers_count = correct_answers.count
    (correct_answers_count == correct_answers.where(id: answer_ids).count) &&
    correct_answers_count == answer_ids.count
  end

  def correct_answers
    current_question.answers.correct_answers
  end

  def next_questions
    test.questions.order(:id).where('id > ?', self.current_question.id)
  end

  def next_question
    next_questions.first
  end

end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController

  before_action :authenticate_user!
  before_action :set_test_passage, only: %i[show update result gist]

  def show
    after_completed_actions
  end

  def result
  end

  def update
    @test_passage.accept!(params[:answer_ids])
    after_completed_actions
  end

  def gist
    gist_question_service = GistQuestionService.new(@test_passage.current_question)
    response = gist_question_service.call

    flash_options = if gist_question_service.last_call_successful?
                      @test_passage.current_question.gists.create(url: response.html_url, user: current_user)
                      { notice: t('.success', url: response.html_url) }
                    else
                      { alert: t('.failure') }
                    end

    redirect_to @test_passage, flash_options
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end

  def after_completed_actions
    if @test_passage.completed?
      actions_if_successful
      TestsMailer.completed_test(@test_passage).deliver_now
      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end

  def actions_if_successful
    if @test_passage.successful?
      @test_passage.update_attribute(:success, true)
      BadgeIssuerService.new(@test_passage).call
    end
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper

  def success_color_string(test_passage)
    if test_passage.successful?
      string_color = 'green'
      result_string = t('test_was_passed')
    else
      string_color = 'red'
      result_string = t('test_was_failed')
    end

    questions_string = t('questions_correct')
    "<span style='color: #{string_color}'>#{test_passage.success_percentage}%</span> #{questions_string}<p>#{result_string}</p>".html_safe
  end
end

app/views/test_passages/_progress_bar.html.erb
<div class="progress">
  <%= content_tag(:div,
                  '0%',
                  class: 'progress-bar',
                  id: 'testPassageProgress',
                  'aria-valuemax': 100,
                  'aria-valuemin': 0,
                  'aria-valuenow': 0,
                  role: 'progressbar',
                  data: {
                    question_number: @test_passage.current_question_number,
                    questions_count: @test_passage.test.questions.count
                  }) %>
</div>

app/views/test_passages/result.html.erb
<div class="row mt-3">
  <div class="col col-md-6">
    <h1><%= t('.header', title: @test_passage.test.title) %></h1>

    <p><%= t('.test_passage_result') %>:</p>
    <p><%= success_color_string(@test_passage) %></p>

    <%= link_to t('.go_back_to_tests'), tests_path %>

  </div>
</div>

app/views/test_passages/show.html.erb
<div class="row mt-3">
  <div class="col col-md-4">

    <h2><%= t('.test_passing') %> <%= @test_passage.test.title %></h2>

    <% if @test_passage.test.questions.any? %>
      <%= render 'progress_bar' %>

      <p><%= t('.total_questions')%>: <%= @test_passage.test.questions.count %></p>
      <p><%= t('.current_question') %>: <%= @test_passage.current_question_number %></p>

      <h2>
        <%= @test_passage.current_question.body %>
      </h2>

      <%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form| %>
        <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :title, include_hidden: false do |b| %>
          <div class="form-check mt-2">
            <%= b.check_box id: "answer_ids_#{b.object.id}", class: 'form-check-input position-static' %>
            <%= b.label class: 'form-check-label'%>
          </div>
        <% end %>

        <p><%= link_to t('.gist_question'), gist_test_passage_path(@test_passage), method: :post %></p>
        <p><%= form.submit t('.next'), class: 'btn btn-primary mt-5' %></p>
      <% end %>

      <% if @test_passage.test.allotted_time != nil %>
        </br></br>
        <p>
          <div class="hide" id="hidden_deadline_time"><%= @test_passage.deadline_time %></div>
          <div class="hide" id="hidden_created_at"><%= @test_passage.created_at %></div>

          <div>
            <%= t('.time_left')%><span id="testPassageTimer"><%= @test_passage.time_left_string %></span>
          </div>
        </p>
      <% end %>

    <% else %>
      <h2>No questions</h2>
    <% end %>

  </div>
</div>