config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'

  devise_for :users,
      path: :gurus,
      path_names: { sign_in: :login, sign_out: :logout },
      controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
       resources :answers, shallow: true, except: :index
      end
    end

    resources :gists, only: :index
    resources :badges
  end

  resources :feedbacks, only: %i[new create]
  resources :badges, only: %i[index]

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  scope :correct_answers, -> { where(correct: true) }

  validates :title, presence: true
  validate :answers_count, on: :create

  private

  def answers_count
    errors.add(:self, 'Question must have only 1-4 answers') unless (0..3).include?(question.answers.count)
  end
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::BaseController
  before_action :find_question, only: %i[ new create]
  before_action :set_answer, only: %i[ show edit update destroy ]

  def show
  end

  def new
    @answer = @question.answers.new
  end

  def edit
  end

  def create
    @answer = @question.answers.new(answer_params)

    if @answer.save
      redirect_to admin_answer_path(@answer), notice: "Answer was successfully created."
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to admin_answer_path(@answer), notice: "Answer was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to admin_question_path(@answer.question), notice: "Answer was successfully destroyed."
  end

  private
    def set_answer
      @answer = Answer.find(params[:id])
    end

    def answer_params
      params.require(:answer).permit(:title, :correct)
    end

    def find_question
      @question = Question.find(params[:question_id])
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/admin/answers/_answer.html.erb
<li>
  <%= answer.title %><br>
  <%= link_to t('.show'), admin_answer_path(answer) %> |
  <%= link_to t('.edit'), edit_admin_answer_path(answer) %> |
  <%= link_to t('.delete'),
      admin_answer_path(answer),
      method: :delete,
      data: {confirm: t('.confirm') } %>
</li>

app/views/admin/answers/_form.html.erb
<%= form_with(model: [:admin, @question, @answer], local: true) do |form| %>
  <%= render 'shared/errors', resource: @answer %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_area :title, id: :answer_title, rows:7, cols: 60 %>
  </p>

  <p>
    <%= form.label :correct %>:
    <%= form.check_box :correct, id: :answer_correct %>
  </p>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/answers/edit.html.erb
<h1>Editing Answer</h1>

<p>
  <%= @answer.question.body %>
</p>

<%= render 'form', answer: @answer %>

<%= link_to t('back'), admin_question_path(@answer.question) %>

app/views/admin/answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Answers</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_admin_answer_path %>

app/views/admin/answers/new.html.erb
<h1>New Answer</h1>

<p>
  <%= @answer.question.body %>
</p>

<%= render 'form', answer: @answer %>

<%= link_to 'Back', admin_question_path(@question) %>

app/views/admin/answers/show.html.erb
<h1><%= t('.question') %></h1>
<p><%= @answer.question.body %></p>

<p>
  <b><%= t('.answer') %></b>
  <%= @answer.title %>
</p>

<p>
  <b><%= t('.correct') %></b>
  <%= @answer.correct %>
</p>

<%= link_to t('edit'), edit_admin_answer_path(@answer) %> |
<%= link_to t('back'), admin_question_path(@answer.question) %>